10.0 sale promotion rule improved lmi
akretion/ak-odoo-incubator pull request #116
Opened 2018-09-03 14:18 UTC by lmignon

Improve code

2018-09-05 13:48 UTC, lmignon commented
@sebastienbeau Here it's a refactoring of the module to support multi rules and improve performances on rule computation.

2018-09-05 14:33 UTC, rvalyi requested changes
some English mistakes...

2018-09-05 14:33 UTC, rvalyi commented on sale_promotion_rule/README.rst
> +This module add the concept of promotion rules that can be applied on the sale
s/add/adds/
s/on the sale order/on a sale order/

2018-09-05 14:33 UTC, rvalyi commented on sale_promotion_rule/README.rst
> +user click on the button "Apply discount" into the view form. Depending of the
s/user click on the button "Apply discount" into the view form/user clicks on the "Apply discount" button in the form view

2018-09-05 14:33 UTC, rvalyi commented on sale_promotion_rule/README.rst
> +order.
s/Depending of/Depending on
s/to a same sale/to a given sale order

2018-09-05 14:33 UTC, rvalyi commented on sale_promotion_rule/README.rst
> +ale.order. This rule takes always precedence over automatic rules.
s/ale.order/sale order

2018-09-12 09:23 UTC, bguillot requested changes
Great improvements ! Thanks !

2018-09-12 09:23 UTC, bguillot commented on sale_promotion_rule/models/sale_promotion_rule.py
> +        auto_rules._apply(orders)
This crashes if several automatic promotions are found, we should remove the ensure_one() in the _apply() method or make a loop here.

2018-09-12 09:23 UTC, bguillot commented on sale_promotion_rule/models/sale_promotion_rule.py
> +    def unset(self, orders):
This method is never called is it usefull ?

2018-09-12 09:23 UTC, bguillot commented on sale_promotion_rule/models/sale_promotion_rule.py
> +            self.reset_promitions()
This method doesn't exists, is it remove_promotions() ?

2018-09-12 11:24 UTC, lmignon commented on sale_promotion_rule/models/sale_promotion_rule.py
> +        auto_rules._apply(orders)
oups... The API has changed a lot of time while implementing the new logic. Indeed, we should make a loop here

2018-09-12 11:24 UTC, lmignon commented on sale_promotion_rule/models/sale_promotion_rule.py
> +    def unset(self, orders):
nor more used... to be removed

2018-09-12 11:34 UTC, lmignon commented on sale_promotion_rule/models/sale_promotion_rule.py
> +        auto_rules._apply(orders)
@bguillot code fixed

2018-09-12 13:03 UTC, bguillot approved these changes

2018-09-12 13:18 UTC, merged