IMP add an explicit notification message (printer name for example)
akretion/ak-odoo-incubator pull request #318
Opened 2024-11-05 15:40 UTC by mourad-ehm

@bealdav

2024-11-06 10:52 UTC, hparfr requested changes
it helps the review when you tell us "why" you are introducing a change

2024-11-06 10:52 UTC, hparfr commented on proxy_action/models/helper.py
> +        msg="Your action is being executed",
no translation anymore ?

2024-11-06 10:52 UTC, hparfr commented on proxy_action/static/src/js/proxy_view.esm.js
> +        if (act.params.args && act.params.args[2] !== undefined) {
why not use kwargs ?

2024-11-06 10:52 UTC, hparfr commented on proxy_action/static/src/js/proxy_view.esm.js
> +        let msg = "Your action is being executed";
this is defined twice and no more translation

2024-11-06 12:39 UTC, bealdav commented
Thanks for the review @hparfr .

@mourad-ehm could you fix it ? Thanks.

2024-11-14 10:22 UTC, mourad-ehm commented on proxy_action/models/helper.py
> +        msg="Your action is being executed",
Twice definition off message removed and message translated

2024-11-14 10:23 UTC, mourad-ehm commented on proxy_action/static/src/js/proxy_view.esm.js
> +        if (act.params.args && act.params.args[2] !== undefined) {
There is any problem to use args

2024-11-14 14:32 UTC, hparfr commented on proxy_action/static/src/js/proxy_view.esm.js
> +        if (act.params.args && act.params.args[2] !== undefined) {
not really human readable / friendly


btw, why the `!==` check ? what values do you expect if `act.params.args[2]`  is `""` or `false` ?

2025-04-03 13:16 UTC, mourad-ehm commented on proxy_action/static/src/js/proxy_view.esm.js
> +        if (act.params.args && act.params.args[2] !== undefined) {
@hparfr modification is made in this commit https://github.com/akretion/ak-odoo-incubator/pull/318/commits/a05576f6110c85fed840b2bcf82f85cfd7782869

2025-04-03 13:20 UTC, hparfr commented
/ocabot merge major

2025-04-03 13:44 UTC, hparfr commented
/ocabot merge major

2025-04-03 13:48 UTC, merged